DOSSEG
.MODEL SMALL
.STACK 100H
.DATA
.CODE
MAIN PROC
	MOV BX,1 ;NUMBER OF STARS TO PRINT
	MOV CX,5 ;COUNTER FOR OUTER LOOP
	L1:
		PUSH CX ;SAVING THE VALUE OF OUTER LOOP'S COUNTER IN STACK
		MOV CX,BX
		L2:
			;PRINTING THE STARS
			MOV DX,'*'
			MOV AH,02
			INT 21H
		LOOP L2
		;ENTER KEY CODE
		MOV DX,10
		MOV AH,02
		INT 21H
		MOV DX,13
		MOV AH,02
		INT 21H
		
		INC BX
		POP CX ;RESTORING THE VALUE FOR OUTER LOOP
	LOOP L1
	MOV AH,4CH
	INT 21H
MAIN ENDP
END MAIN